### ISSUE TITLE
Generate Visual Studio C++ project files

### ISSUE THREAD

**Issue by acomerdigi** [dprogm/vscode-bazel-tools#3]
Would like to see a feature where the tool can read Bazel BUILD/WORKSPACE files and generate a valid .vcproj file

**Comment by dprogm** [comment]
Not sure if this should be better part of a Visual Studio plugin? This plugin actually only works in conjunction with Visual Studio Code and uses internally bazel commands for introspecting the dependency graph.

**Comment by zaucy** [comment]
I believe this is out of the scope of this project. If bazel has first class support for generating project files it should be supported, but as far as I know that isn't a planned feature of bazel.

**Comment by dprogm** [comment]
I close this issue because as @zaucy already said this is out of the projects scope.

**Comment by dwatley** [comment]
For what it's worth I see it seems there's a project that does this according to the new bazel blog post: https://github.com/tmandry/lavender
